
public enum Status {
	NORMAL, FALLBACK, BYPASS, AUTO, MANUAL, ADVISORY, ALARM, LOGGED_ON, LOGGED_OFF,
	PRINT_ON_DEMAND, PRINT_IMMEDIATE, PRINT_LOG, ACTIVE, INACTIVE, PENDING, RUNNING, FINISHED, IDLE,
	ACQUIRING_DL, DL_COMPLETE, ACQUIRING_UL, UL_COMPLETE, STARTED, SUCCESSFUL, FAILED, DENIED,
	DL_FAILED_A, DL_FAILED_B, DL_FAILED_C, DL_FAILED_D, DL_FAILED, NO_SAT
}
